### ISSUE TITLE
Android not working if using react-native-navigation

### ISSUE THREAD

**Issue by gimwee** [Gustash/react-native-giphy-keyboard#12]
Having issues with android where giphy keyboard won't fire up, after some debugging, found out that problem lies in GiphyModule.kt line 70.  

` val activity = reactContext.currentActivity as? ReactActivity ?: return`

If app is using react-native-navigation library, MainActivity class is extends to NavigationActivity instead of ReactActivity,  and since NavigationActivity extends AppCompatActivity, so we have to cast  reactContext.currentActivity as? AppCompatActivity

` import androidx.appcompat.app.AppCompatActivity; `
`val activity = reactContext.currentActivity as? AppCompatActivity ?: return`

Not sure whether this is the correct solutions, as I am not very good in Native Android/Kotlin, if anyone can take a look at this and update code would be great

**Comment by filipef101** [comment]
Not using the package anymore, I would say give it a go and see if you can manage a solution, and open a PR

**Comment by Gustash** [comment]
This package has now been deprecated in favor of the official `@giphy/react-native-sdk` library.
