### ISSUE TITLE
Android build issues ( maven migration )

### ISSUE THREAD

**Issue by raienko** [Gustash/react-native-giphy-keyboard#13]
@Gustash , @filipef101  Hi guys, faced following issues during android build:

```
../node_modules/react-native-giphy-keyboard/android/src/main/java/com/reactnativegiphykeyboard/GiphyModule.kt: (7, 22): Unresolved reference: core
../node_modules/react-native-giphy-keyboard/android/src/main/java/com/reactnativegiphykeyboard/GiphyModule.kt: (8, 22): Unresolved reference: core
../node_modules/react-native-giphy-keyboard/android/src/main/java/com/reactnativegiphykeyboard/GiphyModule.kt: (74, 28): Cannot access class 'com.giphy.sdk.core.models.enums.RatingType'. Check your module classpath for missing or conflicting dependencies
../node_modules/react-native-giphy-keyboard/android/src/main/java/com/reactnativegiphykeyboard/GiphyModule.kt: (74, 28): Cannot access class 'com.giphy.sdk.core.models.enums.RenditionType'. Check your module classpath for missing or conflicting dependencies
../node_modules/react-native-giphy-keyboard/android/src/main/java/com/reactnativegiphykeyboard/GiphyModule.kt: (110, 9): Object is not abstract and does not implement abstract member public abstract fun onGifSelected(media: Media): Unit defined in com.giphy.sdk.ui.views.GiphyDialogFragment.GifSelectionListener
../node_modules/react-native-giphy-keyboard/android/src/main/java/com/reactnativegiphykeyboard/GiphyModule.kt: (112, 9): 'onGifSelected' overrides nothing
../node_modules/react-native-giphy-keyboard/android/src/main/java/com/reactnativegiphykeyboard/GiphyModule.kt: (112, 43): Unresolved reference: Media
```

Seems like `giphy-android-sdk` moved from `http://giphy.bintray.com/giphy-sdk` to maven central
( https://bintray.com announced deprecation )

Please check this commit:
https://github.com/Giphy/giphy-android-sdk/commit/7a880993798f6f221f90569822121efa41877197

### Environment:
"react-native": "0.63.4"
"react-native-giphy-keyboard": "2.0.0"
Platform: Android ( both debug and release )

**Comment by marco-guida** [comment]
@raienko Same issue for me on Android. Removed the ```maven { url 'http://giphy.bintray.com/giphy-sdk' }``` from build.gradle and replaced it with mavenCentral() but had build issues with some of the imports in the module.

**Comment by filipef101** [comment]
doesnt work changing to          mavenCentral()?

**Comment by marco-guida** [comment]
> doesnt work changing to mavenCentral()?

I couldn’t get it to work. After I made the changes I still got the same issues as @raienko when building on Android. Were you able to make it work?

**Comment by marco-guida** [comment]
In the module's build.gradle file, I added ```implementation 'com.giphy.sdk:core:3.1.6'``` below the implementation for ```com.giphy.sdk:ui:1.1.2``` and now it builds. But the app crashes upon startup. The errors were related to core missing so I tried using ```com.giphy.sdk:core```.

**Comment by raienko** [comment]
1. moved to `mavenCentral()` instead of `maven { url 'http://giphy.bintray.com/giphy-sdk' }`
2. added `implementation 'com.giphy.sdk:core:version'` ( tried several versions 3.1.6, 1.0.3, etc )

These steps resolve build issues, but app crashes right on launch ( same issue as @iwantadventureinthegreatwidesomewhere faced ).

**Comment by raienko** [comment]
From logcat:

```
E/AndroidRuntime: FATAL EXCEPTION: create_react_context
    Process: com.xxx.xxx, PID: 14733
    java.lang.AbstractMethodError: abstract method "boolean 
com.facebook.soloader.nativeloader.NativeLoaderDelegate.loadLibrary(java.lang.String, int)"
        at com.facebook.soloader.nativeloader.NativeLoader.loadLibrary(NativeLoader.java:51)
        at com.facebook.soloader.nativeloader.NativeLoader.loadLibrary(NativeLoader.java:30)
        at com.facebook.jni.HybridData.<clinit>(HybridData.java:34)
        at com.facebook.hermes.reactexecutor.HermesExecutor.initHybridDefaultConfig(Native Method)
        at com.facebook.hermes.reactexecutor.HermesExecutor.<init>(HermesExecutor.java:33)
        at com.facebook.hermes.reactexecutor.HermesExecutorFactory.create(HermesExecutorFactory.java:29)
        at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:1017)
        at java.lang.Thread.run(Thread.java:919)

2021-04-26 12:27:18.052 14733-15774/com.xxx.xxx E/GraphResponse: {
  HttpStatus: 400,
  errorCode: 100,
  subErrorCode: 33,
  errorType: GraphMethodException,
  errorMessage: Unsupported get request. Object with ID '715712572117658' does not exist,
  cannot be loaded due to missing permissions, or does not support this operation.
  Please read the Graph API documentation at https://developers.facebook.com/docs/graph-api
}
```

**Comment by raienko** [comment]
@filipef101 could you, please, share your last working ui/core libs versions combination?
Which `com.giphy.sdk:core` version was suitable for `com.giphy.sdk:ui:1.1.2` ?

**Comment by OlegPanfyorov** [comment]
We've faced the same issue! Can someone help? Our release is blocked :( @filipef101

**Comment by filipef101** [comment]
I am no longer working with any project that uses this library. 
CC: @reyalpsirc

**Comment by reyalpsirc** [comment]
We also faced problems with this and in the end we removed the library for Android from the project

**Comment by marco-guida** [comment]
@reyalpsirc What did you use instead? I can make my own version using just the GIPHY API and building the component myself, but it likely won't be as good as the packages dedicated to this.

**Comment by iwantadventureinthegreatwidesomewhere** [comment]
@filipef101 Even though you don't use this with any of your current projects, could you provide us with guidance on how we can tweak this library to resolve this specific issue, or if the change is so significant it isn't worth us patching the package for our individual projects.

**Comment by reyalpsirc** [comment]
@iwantadventureinthegreatwidesomewhere We are not using giphy for now on Android. We just postponed that for later since we had other issues in our hands for now

**Comment by filipef101** [comment]
Reach out via email and I can try to spare some time for this (my username at gmail.com)

**Comment by JulianKingman** [comment]
Try `mavenCentral()` with `implementation 'com.giphy.sdk:ui:2.0.9'`

**Comment by filipef101** [comment]
https://www.youtube.com/watch?v=VHM94Wg92T0

**Comment by filipef101** [comment]
https://github.com/Gustash/react-native-giphy-keyboard/pull/16

**Comment by Gustash** [comment]
This package has now been deprecated in favor of the official `@giphy/react-native-sdk` library.
