### ISSUE TITLE
Kotlin error in Android

### ISSUE THREAD

**Issue by krunalbad** [Gustash/react-native-giphy-keyboard#14]
> Task :react-native-giphy-keyboard:compileDebugKotlin FAILED
w: Runtime JAR files in the classpath should have the same version. These files were found in the classpath:

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-giphy-keyboard:compileDebugKotlin'.
> Compilation error. See log for more details

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 44s

**Comment by Vinicius-O-Neves** [comment]
Hey! Try to change the kotlin version for the last version you installed  
Like -> 
buildscript {
    ext.kotlin_version = "1.5.10"
    repositories {
        google()
        mavenCentral()
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:4.2.1'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath 'com.google.gms:google-services:4.3.8'
        classpath 'com.google.firebase:perf-plugin:1.4.0'
    }
}

**Comment by krunalbad** [comment]
Unfortunately, this didn't fix.....thanks anyway....let me know if there is any other solution @Vinicius-O-Neves

**Comment by krunalbad** [comment]
Yeah man of course this library I am using it lol 😅  @Vinicius-O-Neves 
But the build tool version in my project is not 30
Let me try that and let you know

**Comment by krunalbad** [comment]
Closing this issue since this https://github.com/Gustash/react-native-giphy-keyboard/pull/16 fixes my problem
