### ISSUE TITLE
How to verify GIPHY Integration?

### ISSUE THREAD

**Issue by JoonJoon123** [Gustash/react-native-giphy-keyboard#2]
Hi there, @Gustash 
I added react-native-giphy-keyboard to my react native app but I cannot get the production key because there is no instruction on how to verify Giphy integration.

I tried to verify with the instruction from the link but it did not work.
https://developers.giphy.com/docs/sdk/#verification

If there is a solution, please let me know. 

Thanks in Advance

**Comment by Gustash** [comment]
Ah, I completely forgot about this. I made this package for internal usage at my company and we haven't released yet, so that's why it was overlooked.

I'll take a look at this and add support for it very soon

**Comment by nullnullnull7373** [comment]
Please let me know when you add support for the GIPHY verification.
I'm looking forward to it :)

**Comment by Gustash** [comment]
I'm reopening this so people know this is still an issue

**Comment by Gustash** [comment]
I've added instructions for this on the README. Please update to version 1.1.1

**Comment by MamyChow** [comment]
Hi, i update to v: 1.1.2 and i find key in console logs but when trying to identify i got giphy error like this Verification ID is invalid; please follow above instructions to find the correct one. Did you had this kind of problem?

**Comment by Gustash** [comment]
Not sure. Check if the key you're using the correct one, or try calling their support. I've followed this steps I put on the README on my company and we were able to confirm the integration
