### ISSUE TITLE
pod link static dependencies 

### ISSUE THREAD

**Issue by MamyChow** [Gustash/react-native-giphy-keyboard#3]
Hi,
I try the install but i have this error when i pod install:
The 'Pods-We' target has transitive dependencies that include statically linked binaries: (FirebaseAuth, FirebaseCore, FirebaseCoreDiagnostics, GoogleDataTransportCCTSupport, GoogleDataTransport, FirebaseInstanceID, FirebaseFirestore, FirebaseFunctions, FirebaseMessaging, and FirebaseStorage)

So i tried to create the Bridging Header but it doesn't work. I'm new on the ios native part so do you have more details to handle this error ?

Thank you and have a nice day

**Comment by Gustash** [comment]
You need to use this package as a static library. To do that, remove the `use_frameworks!` from the Podfile and add `pod PINCache, :modular_headers => true` instead

**Comment by MamyChow** [comment]
Ok so i removed use_frameworks! and added pod PINCache, :modular_headers => true and then i installed.
Now i have this problem
<img width="364" alt="Capture d’écran 2020-04-04 à 20 31 55" src="https://user-images.githubusercontent.com/31539767/78458714-b704f380-76b3-11ea-9aa6-e7763401bf03.png">

Did i forgot something ?

**Comment by Gustash** [comment]
What version of this package is on your lock file?

**Comment by MamyChow** [comment]
- react-native-giphy-keyboard (1.0.2)

**Comment by Gustash** [comment]
You should have xcode 11.4 btw, is that the version you have installed?

**Comment by MamyChow** [comment]
Nope my xcode is 11.3.1

**Comment by Gustash** [comment]
That explains it. The latest release fixes an issue with builds on Xcode 11.4. Unfortunately, it breaks builds on any version before that. I'd recommend you to update your xcode and try again

**Comment by MamyChow** [comment]
Ok i upgrade xcode
Now i have this errors :(
<img width="351" alt="Capture d’écran 2020-04-05 à 20 37 36" src="https://user-images.githubusercontent.com/31539767/78506931-6528a000-777d-11ea-9723-e6b23033f9ae.png">

I'm a bit lost =D

**Comment by Gustash** [comment]
I'm a bit lost as well now... I haven't gotten this error yet. What version of react native do you have installed?

**Comment by Gustash** [comment]
Also, what's your minimum iOS version?

**Comment by MamyChow** [comment]
i use react-native: 0.61.1 and i think my min IOS version is 10.0

**Comment by MamyChow** [comment]
Do i need to create Bridging Header ?

**Comment by Gustash** [comment]
Yes, without one xcode can't build Swift or call swift from obj-c

**Comment by MamyChow** [comment]
Ok i created the bridging header. Now it's building from xcode but i have error with react-native run-ios command. I have this kind of error <unknown>:0: error: could not build Objective-C module 'SwiftShims'

**Comment by Gustash** [comment]
I really need more information than that

**Comment by MamyChow** [comment]
this is the error:

CompileSwift normal x86_64 /Users/charly/Documents/React-native/We/ios/Pods/DeepDiff/Sources/Shared/Algorithms/WagnerFischer.swift (in target 'DeepDiff' from project 'Pods')
    cd /Users/charly/Documents/React-native/We/ios/Pods
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swift -frontend -c /Users/charly/Documents/React-native/We/ios/Pods/DeepDiff/Sources/Shared/Array+Extensions.swift /Users/charly/Documents/React-native/We/ios/Pods/DeepDiff/Sources/Shared/Change.swift /Users/charly/Documents/React-native/We/ios/Pods/DeepDiff/Sources/Shared/DeepDiff.swift /Users/charly/Documents/React-native/We/ios/Pods/DeepDiff/Sources/Shared/DiffAware.swift /Users/charly/Documents/React-native/We/ios/Pods/DeepDiff/Sources/Shared/Algorithms/Heckel.swift /Users/charly/Documents/React-native/We/ios/Pods/DeepDiff/Sources/iOS/IndexPathConverter.swift /Users/charly/Documents/React-native/We/ios/Pods/DeepDiff/Sources/Shared/MoveReducer.swift /Users/charly/Documents/React-native/We/ios/Pods/DeepDiff/Sources/iOS/UICollectionView+Extensions.swift /Users/charly/Documents/React-native/We/ios/Pods/DeepDiff/Sources/iOS/UITableView+Extensions.swift -primary-file /Users/charly/Documents/React-native/We/ios/Pods/DeepDiff/Sources/Shared/Algorithms/WagnerFischer.swift -emit-module-path /Users/charly/Documents/React-native/We/ios/build/We/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/DeepDiff.build/Objects-normal/x86_64/WagnerFischer\~partial.swiftmodule -emit-module-doc-path /Users/charly/Documents/React-native/We/ios/build/We/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/DeepDiff.build/Objects-normal/x86_64/WagnerFischer\~partial.swiftdoc -emit-module-source-info-path /Users/charly/Documents/React-native/We/ios/build/We/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/DeepDiff.build/Objects-normal/x86_64/WagnerFischer\~partial.swiftsourceinfo -serialize-diagnostics-path /Users/charly/Documents/React-native/We/ios/build/We/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/DeepDiff.build/Objects-normal/x86_64/WagnerFischer.dia -emit-dependencies-path /Users/charly/Documents/React-native/We/ios/build/We/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/DeepDiff.build/Objects-normal/x86_64/WagnerFischer.d -emit-reference-dependencies-path /Users/charly/Documents/React-native/We/ios/build/We/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/DeepDiff.build/Objects-normal/x86_64/WagnerFischer.swiftdeps -target x86_64-apple-ios8.0-simulator -enable-objc-interop -sdk /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.4.sdk -I /Users/charly/Documents/React-native/We/ios/build/We/Build/Products/Debug-iphonesimulator/DeepDiff -I /Users/charly/Library/Developer/Xcode/DerivedData/We-dgpozbnvopkbzkesuyngtyswbedy/Build/Products/Release-iphonesimulator/DeepDiff -I /Users/charly/Library/Developer/Xcode/DerivedData/We-dgpozbnvopkbzkesuyngtyswbedy/Build/Products/Release-iphonesimulator/react-native-giphy-keyboard -F /Users/charly/Documents/React-native/We/ios/build/We/Build/Products/Debug-iphonesimulator/DeepDiff -enable-testing -g -import-underlying-module -module-cache-path /Users/charly/Documents/React-native/We/ios/build/We/ModuleCache.noindex -swift-version 5 -enforce-exclusivity=checked -Onone -D DEBUG -D COCOAPODS -D COCOAPODS -serialize-debugging-options -Xcc -working-directory -Xcc /Users/charly/Documents/React-native/We/ios/Pods -enable-anonymous-context-mangled-names -Xcc -fmodule-map-file=/Users/charly/Library/Developer/Xcode/DerivedData/We-dgpozbnvopkbzkesuyngtyswbedy/Build/Products/Release-iphonesimulator/DeepDiff/DeepDiff.modulemap -Xcc -fmodule-map-file=/Users/charly/Library/Developer/Xcode/DerivedData/We-dgpozbnvopkbzkesuyngtyswbedy/Build/Products/Release-iphonesimulator/react-native-giphy-keyboard/react_native_giphy_keyboard.modulemap -Xcc -fmodule-map-file=/Users/charly/Documents/React-native/We/ios/Pods/Headers/Public/PINCache/PINCache.modulemap -Xcc -fmodule-map-file=/Users/charly/Documents/React-native/We/ios/Pods/Headers/Public/SSZipArchive/SSZipArchive.modulemap -Xcc -fmodule-map-file=/Users/charly/Documents/React-native/We/ios/Pods/Headers/Public/DeepDiff/DeepDiff.modulemap -Xcc -I/Users/charly/Documents/React-native/We/ios/build/We/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/DeepDiff.build/swift-overrides.hmap -Xcc -iquote -Xcc /Users/charly/Documents/React-native/We/ios/build/We/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/DeepDiff.build/DeepDiff-generated-files.hmap -Xcc -I/Users/charly/Documents/React-native/We/ios/build/We/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/DeepDiff.build/DeepDiff-own-target-headers.hmap -Xcc -I/Users/charly/Documents/React-native/We/ios/build/We/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/DeepDiff.build/DeepDiff-all-non-framework-target-headers.hmap -Xcc -ivfsoverlay -Xcc /Users/charly/Documents/React-native/We/ios/build/We/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/DeepDiff.build/all-product-headers.yaml -Xcc -iquote -Xcc /Users/charly/Documents/React-native/We/ios/build/We/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/DeepDiff.build/DeepDiff-project-headers.hmap -Xcc -iquote -Xcc /Users/charly/Documents/React-native/We/ios/libwebp/src -Xcc -I/Users/charly/Documents/React-native/We/ios/build/We/Build/Products/Debug-iphonesimulator/DeepDiff/include -Xcc -I/Users/charly/Documents/React-native/We/ios/build/We/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/DeepDiff.build/DerivedSources-normal/x86_64 -Xcc -I/Users/charly/Documents/React-native/We/ios/build/We/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/DeepDiff.build/DerivedSources/x86_64 -Xcc -I/Users/charly/Documents/React-native/We/ios/build/We/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/DeepDiff.build/DerivedSources -Xcc -DPOD_CONFIGURATION_DEBUG=1 -Xcc -DDEBUG=1 -Xcc -DCOCOAPODS=1 -module-name DeepDiff -o /Users/charly/Documents/React-native/We/ios/build/We/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/DeepDiff.build/Objects-normal/x86_64/WagnerFischer.o -index-store-path /Users/charly/Documents/React-native/We/ios/build/We/Index/DataStore -index-system-modules
/Users/charly/Documents/React-native/We/ios/Pods/Headers/Public/DeepDiff/DeepDiff.modulemap:1:8: error: redefinition of module 'DeepDiff'
module DeepDiff {
       ^
/Users/charly/Library/Developer/Xcode/DerivedData/We-dgpozbnvopkbzkesuyngtyswbedy/Build/Products/Release-iphonesimulator/DeepDiff/DeepDiff.modulemap:1:8: note: previously defined here
module DeepDiff {
       ^
/Users/charly/Documents/React-native/We/ios/Pods/Headers/Public/DeepDiff/DeepDiff.modulemap:1:8: error: redefinition of module 'DeepDiff'
module DeepDiff {
       ^
/Users/charly/Library/Developer/Xcode/DerivedData/We-dgpozbnvopkbzkesuyngtyswbedy/Build/Products/Release-iphonesimulator/DeepDiff/DeepDiff.modulemap:1:8: note: previously defined here
module DeepDiff {
       ^
<unknown>:0: error: could not build Objective-C module 'SwiftShims'

warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 7.0, but the range of supported deployment target versions is 8.0 to 13.4.99. (in target 'PersonalizedAdConsent-PersonalizedAdConsent' from project 'Pods')
warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 7.0, but the range of supported deployment target versions is 8.0 to 13.4.99. (in target 'Analytics' from project 'Pods')
warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 5.0, but the range of supported deployment target versions is 8.0 to 13.4.99. (in target 'leveldb-library' from project 'Pods')
warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 7.0, but the range of supported deployment target versions is 8.0 to 13.4.99. (in target 'BVLinearGradient' from project 'Pods')
warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 7.0, but the range of supported deployment target versions is 8.0 to 13.4.99. (in target 'abseil' from project 'Pods')
warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 7.0, but the range of supported deployment target versions is 8.0 to 13.4.99. (in target 'CodePush' from project 'Pods')
warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 4.3, but the range of supported deployment target versions is 8.0 to 13.4.99. (in target 'Base64' from project 'Pods')
warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 7.0, but the range of supported deployment target versions is 8.0 to 13.4.99. (in target 'BoringSSL-GRPC' from project 'Pods')
warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 6.0, but the range of supported deployment target versions is 8.0 to 13.4.99. (in target 'JWT' from project 'Pods')
warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 7.0, but the range of supported deployment target versions is 8.0 to 13.4.99. (in target 'RNOpenAppSettings' from project 'Pods')
warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 7.0, but the range of supported deployment target versions is 8.0 to 13.4.99. (in target 'gRPC-C++-gRPCCertificates-Cpp' from project 'Pods')
warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 7.0, but the range of supported deployment target versions is 8.0 to 13.4.99. (in target 'gRPC-Core' from project 'Pods')
warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 7.0, but the range of supported deployment target versions is 8.0 to 13.4.99. (in target 'PersonalizedAdConsent' from project 'Pods')
warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 6.0, but the range of supported deployment target versions is 8.0 to 13.4.99. (in target 'RSKImageCropper' from project 'Pods')
warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 7.0, but the range of supported deployment target versions is 8.0 to 13.4.99. (in target 'Protobuf' from project 'Pods')
warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 7.0, but the range of supported deployment target versions is 8.0 to 13.4.99. (in target 'gRPC-C++' from project 'Pods')
warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 7.0, but the range of supported deployment target versions is 8.0 to 13.4.99. (in target 'GTMSessionFetcher' from project 'Pods')
warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 4.3, but the range of supported deployment target versions is 8.0 to 13.4.99. (in target 'nanopb' from project 'Pods')
warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 5.0, but the range of supported deployment target versions is 8.0 to 13.4.99. (in target 'PINCache' from project 'Pods')
warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 7.0, but the range of supported deployment target versions is 8.0 to 13.4.99. (in target 'RNScreens' from project 'Pods')
warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 7.0, but the range of supported deployment target versions is 8.0 to 13.4.99. (in target 'react-native-viewpager' from project 'Pods')
warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 6.0, but the range of supported deployment target versions is 8.0 to 13.4.99. (in target 'libwebp' from project 'Pods')

** BUILD FAILED **


The following build commands failed:
	CompileSwift normal x86_64 /Users/charly/Documents/React-native/We/ios/Pods/DeepDiff/Sources/Shared/Array+Extensions.swift
	CompileSwift normal x86_64 /Users/charly/Documents/React-native/We/ios/Pods/DeepDiff/Sources/Shared/Change.swift
	CompileSwift normal x86_64 /Users/charly/Documents/React-native/We/ios/Pods/DeepDiff/Sources/Shared/DeepDiff.swift
	CompileSwift normal x86_64 /Users/charly/Documents/React-native/We/ios/Pods/DeepDiff/Sources/Shared/DiffAware.swift
	CompileSwift normal x86_64 /Users/charly/Documents/React-native/We/ios/Pods/DeepDiff/Sources/Shared/Algorithms/Heckel.swift
	CompileSwift normal x86_64 /Users/charly/Documents/React-native/We/ios/Pods/DeepDiff/Sources/iOS/IndexPathConverter.swift
	CompileSwift normal x86_64 /Users/charly/Documents/React-native/We/ios/Pods/DeepDiff/Sources/Shared/MoveReducer.swift
	CompileSwift normal x86_64 /Users/charly/Documents/React-native/We/ios/Pods/DeepDiff/Sources/iOS/UICollectionView+Extensions.swift
	CompileSwift normal x86_64 /Users/charly/Documents/React-native/We/ios/Pods/DeepDiff/Sources/iOS/UITableView+Extensions.swift
	CompileSwift normal x86_64 /Users/charly/Documents/React-native/We/ios/Pods/DeepDiff/Sources/Shared/Algorithms/WagnerFischer.swift
	CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler

**Comment by Gustash** [comment]
This doesn't seem related to this package anymore. The steps I've given you should give you a working build. The only thing I can suggest now is you try to run `pod deintegrate`, followed by `pod install`, then do a clean build. If these steps don't work, post your Podfile so I can try to figure it out, but this seems to be a job for Google at this point

**Comment by MamyChow** [comment]
Ok. I tried but it's not working, it's weird because it's working if i run with xcode but note with react-native run-ios.
This is my podfile:
platform :ios, '10.0'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

target 'We' do
  permissions_path = '../node_modules/react-native-permissions/ios'
  pod 'Permission-LocationAlways', :path => "#{permissions_path}/LocationAlways.podspec"
  pod 'Permission-LocationWhenInUse', :path => "#{permissions_path}/LocationWhenInUse.podspec"
  pod 'Permission-Notifications', :path => "#{permissions_path}/Notifications.podspec"
  pod 'Permission-Camera', :path => "#{permissions_path}/Camera.podspec"
  pod 'Permission-PhotoLibrary', :path => "#{permissions_path}/PhotoLibrary.podspec"

   Pods for We
  pod 'FBLazyVector', :path => "../node_modules/react-native/Libraries/FBLazyVector"
  pod 'FBReactNativeSpec', :path => "../node_modules/react-native/Libraries/FBReactNativeSpec"
  pod 'RCTRequired', :path => "../node_modules/react-native/Libraries/RCTRequired"
  pod 'RCTTypeSafety', :path => "../node_modules/react-native/Libraries/TypeSafety"
  pod 'React', :path => '../node_modules/react-native/'
  pod 'React-Core', :path => '../node_modules/react-native/'
  pod 'React-CoreModules', :path => '../node_modules/react-native/React/CoreModules'
  pod 'React-Core/DevSupport', :path => '../node_modules/react-native/'
  pod 'React-RCTActionSheet', :path => '../node_modules/react-native/Libraries/ActionSheetIOS'
  pod 'React-RCTAnimation', :path => '../node_modules/react-native/Libraries/NativeAnimation'
  pod 'React-RCTBlob', :path => '../node_modules/react-native/Libraries/Blob'
  pod 'React-RCTImage', :path => '../node_modules/react-native/Libraries/Image'
  pod 'React-RCTLinking', :path => '../node_modules/react-native/Libraries/LinkingIOS'
  pod 'React-RCTNetwork', :path => '../node_modules/react-native/Libraries/Network'
  pod 'React-RCTSettings', :path => '../node_modules/react-native/Libraries/Settings'
  pod 'React-RCTText', :path => '../node_modules/react-native/Libraries/Text'
  pod 'React-RCTVibration', :path => '../node_modules/react-native/Libraries/Vibration'
  pod 'React-Core/RCTWebSocket', :path => '../node_modules/react-native/'

  pod 'React-cxxreact', :path => '../node_modules/react-native/ReactCommon/cxxreact'
  pod 'React-jsi', :path => '../node_modules/react-native/ReactCommon/jsi'
  pod 'React-jsiexecutor', :path => '../node_modules/react-native/ReactCommon/jsiexecutor'
  pod 'React-jsinspector', :path => '../node_modules/react-native/ReactCommon/jsinspector'
  pod 'ReactCommon/jscallinvoker', :path => "../node_modules/react-native/ReactCommon"
  pod 'ReactCommon/turbomodule/core', :path => "../node_modules/react-native/ReactCommon"
  pod 'Yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec', :modular_headers => false
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec', :modular_headers => false
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec', :modular_headers => false
  pod 'PINCache', :modular_headers => true


  target 'WeTests' do
    inherit! :search_paths
     Pods for testing
  end

  use_native_modules!
end

target 'We-tvOS' do
  Pods for We-tvOS

  target 'We-tvOSTests' do
    inherit! :search_paths
    Pods for testing
  end

end

**Comment by Gustash** [comment]
Okay, I don't see anything necessarily wrong with your Podfile. If you can build with xcode then I assume it's a react native issue. I'd recommend you use xcode to build instead of `react-native run-ios` for now. I'm closing this as it seems the original issue has been fixed, and this is no longer related to this package.

**Comment by MamyChow** [comment]
OK thx for your help. And just to know is there a way to verify Giphy integration?

**Comment by Gustash** [comment]
Not yet, there is another pending issue related to that, and it'll probably be coming in the next few weeks as I need it at my job to roll out to production anyway. I'll tag you here when it's available

**Comment by Gustash** [comment]
@MamyChow just released version 1.1.1. I've added verification mode instructions on the README
