### ISSUE TITLE
Cannot load underlying module for 'DeepDiff'

### ISSUE THREAD

**Issue by joshuadiezmo** [Gustash/react-native-giphy-keyboard#6]
this is a clean project from scratch.

![Screen Shot 2020-04-25 at 4 30 33 PM](https://user-images.githubusercontent.com/8644115/80275178-1d5cbf00-8712-11ea-91ff-7bee5b7105b8.png)

**Comment by Gustash** [comment]
Can you let me know what RN version you're using and show me your Podfile?

**Comment by Gustash** [comment]
@joshuadiezmo could you send me over those details so I can look into this for you?

**Comment by Gustash** [comment]
This seems to be the same issue as #7 which is responsing to me, so I'm closing this one as it's a dupe and stale

**Comment by filipef101** [comment]
@joshuadiezmo Did you manage to solve this without use_frameworks?
