### ISSUE TITLE
iOS build broken

### ISSUE THREAD

**Issue by brandonpearcy** [Gustash/react-native-giphy-keyboard#8]
React Native iOS build appears to be broken at head. 

Steps to reproduce

Creating a fresh react-native project (v0.63.3), and confirm it works:
$ npx react-native init MyApp
$ cd MyApp
$ yarn ios && yarn start

Now add giphy keyboard:

$ yarn add react-native-giphy-keyboard
$ (cd ios; pod install)
Open `ios/MyApp.xcodeproj`
New file: Blank.swift
Create Bridging Header
$ yarn ios

Build error:

/Users/bpearcy/src/react-native-latest/MyApp/node_modules/react-native-giphy-keyboard/ios/EnumExtensions.swift:2:8: error: failed to load module 'GiphyUISDK'
import GiphyUISDK

** BUILD FAILED **
The following build commands failed:
	CompileSwift normal x86_64 /Users/bpearcy/src/react-native-latest/MyApp2/node_modules/react-native-giphy-keyboard/ios/EnumExtensions.swift
	CompileSwift normal x86_64 /Users/bpearcy/src/react-native-latest/MyApp2/node_modules/react-native-giphy-keyboard/ios/RNGiphyKeyboard.swift
	CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler
(3 failures)

**Comment by filipef101** [comment]
check my pull request, with  XCode 12.1 and my fork you should be able to build

**Comment by Gustash** [comment]
@filipef101's PR has been merged and released on npm as v2.0.0. Please update the package on your project to fix this issue. Closing.
